### ISSUE TITLE
Using the Batteries test with `uint32` integer types.

### ISSUE THREAD

**Issue by zoj613** [LesBoloss-es/ocaml-testu01#1]
It seems as though the C library supports testing random streams using unsigned 32 integers. However the `TestU01.Unif01.create_extern_gen_int32` function expected signed 32bit integers. This seems to be a problem for my case when using a PRNG that returns a `Stdint.uint32` width integer. I have to cast the value to 32bit using `Stdint.Uint32.to_int32`. This is an issue if the value of the uint32 integer is larger than 2147483647. Casting to int32 returns a negative 32bit number which then gets passed to the batteries test. This then results in the PRNG unexpectedly failing even the SmallCrush test.

For more context, I have a library implementing PRNG's using `Stdint.uint64` and `Stdint.uint32` types [here](https://github.com/zoj613/bitgenerators). If I try to use this testu01 wrapper by casting each uint32 random value to int32, some of them end being negative numbers. For example:

```ocaml
Uint32.of_string "4294967195" |> Uint32.to_int32;;
(* - : int32 = -101l *)
```
This causes PRNGs known to easily pass BigCrush to fail for SmallCrush due to getting passed the "wrong" values.

My question is: Is there a way to support uint32 PRNG's in this library? Or is there a workaround I can employ to prevent this unwanted behavior?
Currently [this](https://github.com/zoj613/bitgenerators/blob/f2f0a3ae53c3049349897b40ece6d662c43aa3fb/bin/crush.ml#L42-L44) is the scheme I employ but this is obviously buggy.

**Comment by Niols** [comment]
Hi @zoj613; nice to meet you!

I saw your announcement for [bitgenerators](https://github.com/zoj613/bitgenerators) on the OCaml Discuss the other day; it brought me back to when @Kerl13 and I played with [Xoshiro](https://github.com/LesBoloss-es/xoshiro) and made these bindings for TestU01. Funny to see you here!

I'm a big puzzled by your issue. The `int32` type from standard library represents both signed and unsigned integers; the user chooses what operations to run on them (for instance `Int32.div` and `Int32.unsigned_div` both manipulate `int32` values). With your example:
```ocaml
# Int64.(of_string "4294967195" |> to_int32);;
- : int32 = -101l
```
but:
```ocaml
# Int64.(of_string "4294967195" |> to_int32) |> Format.printf "%lu@.";;
4294967195
- : unit = ()
```
Personally, I think this is awful and I'd much prefer having two distinct types with distinct operations, like `Stdint` provides.

Looking at [the code](https://github.com/LesBoloss-es/ocaml-testu01/blob/main/testu01/unif01_stubs.c#L109-L132) for `create_extern_gen_int32`, it looks legit to me, but I might be missing something. Could you try testing your generator on 30-bit integers? This would consist in taking your function `(to_module !prng |> make_int32 ~rev:!rev)` (I'll call it `gen`) and calling `create_extern_gen_bits ... (fun () -> gen () lsr 2)` instead of `create_extern_gen_int32 ... gen`. If I read the stubs correctly, this should only create a weaker generator (because of the two bits we drop), and therefore it should only pass less tests of the TestU01 suite. Let's see.

I see [Pringo](https://ocaml.org/p/pringo/1.4) and [Randii](https://ocaml.org/p/randii/1.0.0) both use our library to test their generators, so maybe there is some inspiration to find over there. [Xoshiro](https://github.com/LesBoloss-es/xoshiro) also relies on our library but only tests a function that produces 30-bits.

I'm not sure this is all super useful to you; but I'm sure we'll get there!

**Comment by zoj613** [comment]
Hi @Niols , thanks a lot for the detailed response. It looks like the problem went away once I used a sensible/default p-value for the tests instead of `0.01`. So closing this.

**Comment by Niols** [comment]
Good to hear!
